### ISSUE TITLE
`rm .gitmodules` 和`rm -r themes/default` 在windows10上可能报错，从而导致网页无法打开

### ISSUE THREAD

**Issue by DreamBroke** [michaelliao/gitsite#3]
这是我的cmd logs:
```
D:\Blog>gitsite-cli init
prepare init new git site...
downloading sample gitsite from https://codeload.github.com/michaelliao/gitsite/zip/refs/heads/main...
unzip to: .github/workflows/gitsite.yml
unzip to: .gitignore
unzip to: .gitlab-ci.yml
unzip to: .gitmodules
unzip to: LICENSE
unzip to: README.md
unzip to: source/404.md
unzip to: source/README.md
unzip to: source/blogs/tech/2024-01-01-hello-world/README.md
unzip to: source/blogs/tech/2024-01-01-hello-world/emoji-silly.png
unzip to: source/blogs/tech/2024-01-02-document-ready/README.md
unzip to: source/blogs/tech/2024-01-02-document-ready/document-ready.png
unzip to: source/blogs/tech/2024-01-03-execute-js-innerhtml/README.md
unzip to: source/blogs/tech/2024-01-04-flex-search/README.md
unzip to: source/blogs/tech/2024-01-04-flex-search/search.png
unzip to: source/books/gitsite-guide/10-introduction/README.md
unzip to: source/books/gitsite-guide/20-install/README.md
unzip to: source/books/gitsite-guide/20-install/ci-cd-vars.png
unzip to: source/books/gitsite-guide/20-install/home.png
unzip to: source/books/gitsite-guide/30-organizing/README.md
unzip to: source/books/gitsite-guide/40-write-content/10-basic-syntax/README.md
unzip to: source/books/gitsite-guide/40-write-content/10-basic-syntax/cat.png
unzip to: source/books/gitsite-guide/40-write-content/20-table/README.md
unzip to: source/books/gitsite-guide/40-write-content/30-code-blocks/README.md
unzip to: source/books/gitsite-guide/40-write-content/40-alerts/README.md
unzip to: source/books/gitsite-guide/40-write-content/50-videos/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/10-math/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/20-ascii/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/30-qrcode/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/30-qrcode/like.png
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/40-diagrams/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/50-questions/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/60-music/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/70-digital-timing/README.md
unzip to: source/books/gitsite-guide/40-write-content/60-advanced-formatting/README.md
unzip to: source/books/gitsite-guide/40-write-content/README.md
unzip to: source/books/gitsite-guide/50-customize/README.md
unzip to: source/books/gitsite-guide/60-dev-guide/README.md
unzip to: source/books/gitsite-guide/AFTER.md
unzip to: source/books/gitsite-guide/BEFORE.md
unzip to: source/books/gitsite-guide/book.yml
unzip to: source/favicon.ico
unzip to: source/pages/license/README.md
unzip to: source/site.yml
unzip to: source/static/custom.css
unzip to: source/static/custom.js
unzip to: source/static/logo.svg
unzip ok.
init git repository:
> rm .gitmodules
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
command failed:
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


> rm -r themes/default
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
command failed:
'rm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


> git init
Initialized empty Git repository in D:/Blog/.git/

add default theme as submodule:
> git submodule add https://github.com/michaelliao/gitsite-theme-default.git themes/default
fatal: 'themes/default' already exists and is not a valid git repo
command failed:
fatal: 'themes/default' already exists and is not a valid git repo



----------------------------------------------------------------------

Your git site was initialized successfully!
Please edit source/site.yml to customize your site.

To start the server and preview your site on http://localhost:3000

    gitsite-cli serve -v

To build your site:

    gitsite-cli build -v

To get more information on GitSite please visit https://gitsite.org



D:\Blog>gitsite-cli serve
source dir: D:\Blog\source
themes dir: D:\Blog\themes
cache dir: D:\Blog\.cache
generate search index...
generate search index for book: gitsite-guide
generate search index for blog: Full Text Search by Pure JavaScript
generate search index for blog: How to Execute JavaScript when Using innerHTML
generate search index for blog: Document Ready Equivalent without jQuery
generate search index for blog: Hello, World
generate search index for page: license
export index: string / reg: string
export index: string / cfg: string
export index: string / map: string
export index: string / ctx: string
waiting for export index...
generated search index: 37.5 kb
set gitsite directory: D:\Blog\source
server is running at port 3000...
GET: /
use markdown plugin mermaid.
load svg from cache: D:\Blog\.cache\u21e9135.svg
C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:234
        err = new Error('template not found: ' + name);
              ^

Error: template not found: index.html
    at createTemplate (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:234:15)
    at next (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\lib.js:260:7)
    at handle (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:267:11)
    at C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:276:9
    at next (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\lib.js:258:7)
    at Object.asyncIter (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\lib.js:263:3)
    at Environment.getTemplate (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:259:9)
    at Environment.render (C:\Users\木数难数\AppData\Roaming\npm\node_modules\gitsite-cli\node_modules\nunjucks\src\environment.js:295:10)
    at renderTemplate (file:///C:/Users/%E6%9C%A8%E6%95%B0%E9%9A%BE%E6%95%B0/AppData/Roaming/npm/node_modules/gitsite-cli/bin/index.js:229:33)
    at processSpecialPage (file:///C:/Users/%E6%9C%A8%E6%95%B0%E9%9A%BE%E6%95%B0/AppData/Roaming/npm/node_modules/gitsite-cli/bin/index.js:720:9)

Node.js v20.10.0
```
手动删除文件夹后，再手动运行 `git submodule add https://github.com/michaelliao/gitsite-theme-default.git themes/default` 可以修复。

我的Windows版本信息：
```
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2020/‎11/‎26
操作系统内部版本	19045.4529
体验	Windows Feature Experience Pack 1000.19058.1000.0
```

**Comment by michaelliao** [comment]
fixed.

https://github.com/michaelliao/gitsite-cli/commit/3930ebdd2171e2b3942662fa67165cd28e4686f0

**Comment by michaelliao** [comment]
update to latest version:

`npm update -g gitsite-cli`
